import Link from 'next/link';
import { ArrowDown, ArrowUpRight, Flower2, MoveRight, Search, SlidersHorizontal } from 'lucide-react';
import { categories } from '@sahaj/shared';
import { catalogQuerySchema, listProducts } from '@/lib/catalog';
import { db } from '@/lib/db';
import { ProductCard, Values, EmptyState } from '@/components/site';

export const dynamic = 'force-dynamic';
export default async function Home({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const parsed = catalogQuerySchema.safeParse({ search: params.search || '', category: params.category || undefined, sort: params.sort || 'newest' });
  const query = parsed.success ? parsed.data : catalogQuerySchema.parse({});
  const [products, sellers] = await Promise.all([listProducts(query), db.seller.findMany({ where: { products: { some: { isPublished: true } } }, orderBy: { id: 'asc' }, take: 3 })]);
  const filtered = !!query.search || !!query.category;
  return <>
    <section className="hero wrap"><div className="hero-copy"><span className="eyebrow"><span className="tiny-line" /> A quieter kind of beautiful</span><h1>Not just made.<br /><em>Made to mean<br />something.</em></h1><p>Woven stories. Earth-shaped wonders. Discover everyday objects with a little more soul, straight from the hands that make them.</p><Link href="#collection" className="button">Find your everyday treasure <MoveRight size={19} /></Link><div className="hero-note"><span className="hand-mark">s.</span><span>Rooted in tradition.<br /><strong>Made for the way you live.</strong></span></div></div><div className="hero-art"><img src="/art/hero.svg" alt="An earthen terracotta vase, woven basket, and brass bowl arranged in warm afternoon light" width="900" height="1000" fetchPriority="high" /><span className="hero-art-label">THE BEAUTY OF SLOWLY MADE</span><div className="hero-caption"><span>From earth, with love.<small>Discover the pottery collection</small></span><Link href="/?category=Pottery+%26+Terracotta#collection" aria-label="Explore pottery"><ArrowUpRight /></Link></div><span className="hero-stamp">a human touch<br /><Flower2Mark /><br />in every piece</span></div></section>
    <Values />
    <section className="collection wrap" id="collection"><div className="section-heading"><div><span className="eyebrow">Considered objects. Extraordinary hands.</span><h2>The handmade edit<span>.</span></h2></div><p>For the corners you love.<br />For the people you hold close.</p></div>
      <form key={JSON.stringify(query)} className="catalog-tools" action="/#collection"><label className="search-field"><Search size={19} /><span className="sr-only">Search products or makers</span><input name="search" placeholder="Find something that feels like you..." defaultValue={query.search} /><button type="submit" aria-label="Search"><MoveRight size={20} /></button></label><label className="select-field"><SlidersHorizontal size={16} /><span className="sr-only">Category</span><select name="category" defaultValue={query.category || ''}><option value="">All crafts</option>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label className="select-field"><span className="sr-only">Sort products</span><select name="sort" defaultValue={query.sort}><option value="newest">Newest arrivals</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></label><button className="button small" type="submit">Apply</button></form>
      <div className="category-links"><Link className={!query.category ? 'active' : ''} href={`/?search=${encodeURIComponent(query.search)}&sort=${query.sort}#collection`}>All the beautiful things</Link>{categories.slice(0, 7).map(c => <Link className={query.category === c ? 'active' : ''} key={c} href={`/?category=${encodeURIComponent(c)}&search=${encodeURIComponent(query.search)}&sort=${query.sort}#collection`}>{c.split(' & ')[0]}</Link>)}</div>
      <div className="results-line"><span>{products.length} thoughtfully made {products.length === 1 ? 'piece' : 'pieces'}{query.search && <> for &ldquo;{query.search}&rdquo;</>}</span>{filtered ? <Link href="/#collection">Clear filters</Link> : <span>Small batches. One-of-a-kind character. <ArrowDown size={13} /></span>}</div>
      {!parsed.success && <p className="notice">Those filters were not recognized. Showing the full collection.</p>}
      {products.length ? <div className="product-grid">{products.map((p, i) => <ProductCard key={p.id} product={p} index={i} />)}</div> : <EmptyState title="A little more exploring?" description="No pieces match these filters. Try another craft or a simpler search." />}
    </section>
    <section className="story-section" id="makers"><div className="wrap story-grid"><div className="story-intro"><span className="eyebrow">Behind every piece, a person</span><h2>Good things<br />have <em>human roots.</em></h2><p>A loom passed down. A skill learned at a grandmother's side. Meet the independent makers keeping their craft alive, one thoughtful piece at a time.</p><Link className="text-link" href="#collection">Bring a little of their story home <MoveRight size={18} /></Link></div><div className="maker-list">{sellers.map((seller, i) => <article className="maker" key={seller.id}><span className={`maker-avatar avatar-${i}`}>{seller.name.split(' ').map(n => n[0]).slice(0, 2).join('')}</span><div><span className="eyebrow">{seller.location}</span><h3>{seller.name}</h3><p>{seller.story}</p></div><Link href={`/?search=${encodeURIComponent(seller.name)}#collection`} aria-label={`Shop pieces by ${seller.name}`}><ArrowUpRight /></Link></article>)}</div></div></section>
    <section className="closing wrap"><span className="eyebrow">A home is a collection of stories</span><h2>Make room for <em>something meaningful.</em></h2><Link href="#collection" className="button">Explore the collection <MoveRight size={18} /></Link></section>
  </>;
}
function Flower2Mark() { return <Flower2 size={28} strokeWidth={1} style={{ display: 'inline-block', verticalAlign: 'middle', marginBlock: 3 }} />; }
